# Generated by Django 4.2.21 on 2025-06-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='class_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Đánh giá lớp học'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='teacher_rate',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Đánh giá giáo viên'),
        ),
    ]
