# Generated by Django 4.2.21 on 2025-06-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_feedback_class_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollments',
            old_name='final',
            new_name='final_test',
        ),
    ]
