# Generated by Django 4.2.21 on 2025-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_final_enrollments_final_test'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollments',
            name='final_in_range',
        ),
        migrations.AddConstraint(
            model_name='enrollments',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('final_test__gte', 0), ('final_test__lte', 10)), ('final_test__isnull', True), _connector='OR'), name='final_in_range'),
        ),
    ]
